CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    difficulty_level INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO course (name, category, difficulty_level) VALUES ('Java Basics', 'Programming', 1);
INSERT INTO course (name, category, difficulty_level) VALUES ('Spring Boot Essentials', 'Programming', 3);
INSERT INTO course (name, category, difficulty_level) VALUES ('Web Development with HTML/CSS', 'Web Development', 2);
INSERT INTO course (name, category, difficulty_level) VALUES ('Database Design', 'Databases', 4);
INSERT INTO course (name, category, difficulty_level) VALUES ('Advanced JavaScript', 'Web Development', 5);
INSERT INTO course (name, category, difficulty_level) VALUES ('Python for Data Science', 'Programming', 3);
INSERT INTO course (name, category, difficulty_level) VALUES ('React JS Fundamentals', 'Web Development', 3);